#!/bin/bash
set -v
mysql -h dbhost.cs.man.ac.uk -u y62154ab -p 2018_comp10120_y7  << EOF

DROP TABLE IF EXISTS Hosts;
DROP TABLE IF EXISTS Players;

CREATE TABLE Hosts(
  host_id int NOT NULL AUTO_INCREMENT,
  quiz_code VARCHAR(5) NOT NULL,
  state ENUM("intro", "ask", "answer", "outro") NOT NULL DEFAULT "intro",
  time_since_start int NOT NULL DEFAULT 0,
  PRIMARY KEY (game_id));

CREATE TABLE Players(
  player_id int NOT NULL AUTO_INCREMENT,
  host_id int NOT NULL,
  screen_name VARCHAR(20) NOT NULL,
  answer ENUM("A", "B", "C", "D", "-") NOT NULL DEFAULT "-",
  PRIMARY KEY(player_id));

INSERT INTO game_test VALUES
  (NULL, "TEST1", "intro");
quit
EOF

