#!/bin/bash
set -v
mysql -h dbhost.cs.man.ac.uk -u y62154ab -p 2018_comp10120_y7  << EOF

DROP TABLE IF EXISTS hosts;
DROP TABLE IF EXISTS players;

CREATE TABLE hosts(
  host_id int NOT NULL AUTO_INCREMENT,
  quiz_code VARCHAR(5) NOT NULL,
  state ENUM("intro", "ask", "answer", "outro") NOT NULL DEFAULT "intro",
  timeSinceStart int NOT NULL DEFAULT 0,
  PRIMARY KEY (host_id));

CREATE TABLE players(
  player_id int NOT NULL AUTO_INCREMENT,
  host_id int NOT NULL,
  answer ENUM("A", "B", "C", "D", "-") NOT NULL DEFAULT "-",
  timeSinceStart int NOT NULL DEFAULT 0,
  screen_name VARCHAR(20) NOT NULL,
  PRIMARY KEY(player_id));
  
quit
EOF

