#!/bin/bash
set -v
mysql -h dbhost.cs.man.ac.uk -u y62154ab -p 2018_comp10120_y7  << EOF

DROP TABLE IF EXISTS hosts;
DROP TABLE IF EXISTS players;

CREATE TABLE hosts(
  host_id int NOT NULL AUTO_INCREMENT,
  quiz_code VARCHAR(6) NOT NULL,
  quiz_id int NOT NULL,
  state ENUM("intro", "floating", "question", "feedback", "outro") NOT NULL DEFAULT "intro",
  current_question_id int NOT NULL default 0,
  start_time DATETIME NOT NULL DEFAULT NOW(),
  last_update DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (host_id));

CREATE TABLE players(
  player_id int NOT NULL AUTO_INCREMENT,
  host_id int NOT NULL,
  answer ENUM("A", "B", "C", "D", "-") NOT NULL DEFAULT "-",
  start_time DATETIME NOT NULL DEFAULT NOW(),
  last_update DATETIME NOT NULL DEFAULT NOW(),
  screen_name VARCHAR(20) NOT NULL,
  connected BIT NOT NULL DEFAULT 1,
  PRIMARY KEY(player_id));
  
quit
EOF

