#!/bin/bash
set -v
mysql -h dbhost.cs.man.ac.uk -u y62154ab -p 2018_comp10120_y7  << EOF

DROP TABLE IF EXISTS quizzes;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS answers;

CREATE TABLE  quizzes(
  quiz_id int NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  user_id int NOT NULL,
  PRIMARY KEY (quiz_id));
  
CREATE TABLE questions(
  question_id int NOT NULL AUTO_INCREMENT,
  quiz_id int NOT NULL,
  text VARCHAR(255) NOT NULL,
  x_coord int NOT NULL,
  y_coord int NOT NULL,
  time int NOT NULL,
  feedback VARCHAR(255) NOT NULL,
  PRIMARY KEY(question_ID));
  
CREATE TABLE answers(
  answer_id int NOT NULL AUTO_INCREMENT,
  question_id int NOT NULL,
  text VARCHAR(255) NOT NULL,
  is_correct BIT NOT NULL,
  letter ENUM("A", "B", "C", "D") NOT NULL,
  PRIMARY KEY(answer_id));
  
INSERT INTO quizzes(name, user_id) VALUES("Test Quiz", 1);
INSERT INTO questions VALUES (NULL, 1, "What is 9 squared?", 0, 0, 10, "9 * 9  = 81."),
                             (NULL, 1, "What is the capital of England?", 1, 0, 10, "London is the capital of England."),
                             (NULL, 1, "When was the London fire?", 1, 1, 15, "The London fire was from 2nd September to 6th September in 1666."), 
                             (NULL, 1, "What bear colours exist?", 2, 0, 10, "Brown and black bears appear naturally in the wild."),
                         (NULL, 1, "What letter does London start with?", 1, 2, 10, "The first letter of London is the letter 'L'.");
INSERT INTO answers VALUES
  (NULL, 1, "81", 1, "A"),
  (NULL, 1, "3", 0, "B"),
  (NULL, 2, "Manchester", 0, "A"),
  (NULL, 2, "Paris", 0, "B"),
  (NULL, 2, "London", 1, "C"),
  (NULL, 2, "Ireland", 0, "D"),
  (NULL, 3, "1666", 1, "A"),
  (NULL, 3, "2095", 0, "B"),
  (NULL, 4, "Brown", 1, "A"),
  (NULL, 4, "Pink", 0, "B"),
  (NULL, 4, "Black", 1, "C"),
  (NULL, 5, "L", 1, "A"),
  (NULL, 5, "O", 0, "B");

INSERT INTO quizzes(name, user_id) VALUES("Something", 1);
INSERT INTO quizzes(name, user_id) VALUES("SomethingElse", 1);
INSERT INTO quizzes(name, user_id) VALUES("Ulis Ultimate Quiz", 8);
  
quit
EOF

