#!/bin/bash

mysql -h dbhost.cs.man.ac.uk -u j25802rk -p 2018_comp10120_y7  << EOF

DROP TABLE IF EXISTS users;

CREATE TABLE users(
  user_id int NOT NULL AUTO_INCREMENT,
  username VARCHAR(20) NOT NULL,
  password CHAR(255),
  quizCode CHAR(10),
  PRIMARY KEY (user_id));

INSERT INTO users(username, password, quizCode) VALUES ("Jim", "\$2y\$10\$e301./O6DY7j07fUmCZPOuGvmstHPbV204HcKNcvDA/xN2DV1Lr5C","JIMQUZ");

quit
EOF

#The password inserted into Users is 'password' but hashed

