#!/bin/bash
set -v
mysql -h dbhost.cs.man.ac.uk -u y62154ab -p 2018_comp10120_y7  << EOF

DROP TABLE IF EXISTS game_test;
DROP TABLE IF EXISTS player_test;

CREATE TABLE game_test(
  game_id int NOT NULL AUTO_INCREMENT,
  quiz_code VARCHAR(5) NOT NULL,
  state ENUM("intro", "ask", "answer", "outro"),
  PRIMARY KEY (game_id));

CREATE TABLE player_test(
  player_id int NOT NULL AUTO_INCREMENT,
  game_id int NOT NULL,
  answer ENUM("A", "B", "C", "D"),
  PRIMARY KEY(player_id));

INSERT INTO game_test VALUES
  (NULL, "TEST1", "intro");
quit
EOF

